# BÁO CÁO PROJECT I LẦN 2
Người thực hiện: Nguyễn Mạnh Thắng - 20235426  
Ngưới hướng dẫn: Phạm Minh Tuấn

## Loading all libraries

In [1]:
pip install -r requirements.txt

Requirement already satisfied: numpy in c:\users\ad\documents\project1_venv\lib\site-packages (from -r requirements.txt (line 1)) (2.3.4)
Requirement already satisfied: pandas in c:\users\ad\documents\project1_venv\lib\site-packages (from -r requirements.txt (line 2)) (2.3.3)
Requirement already satisfied: scikit-learn in c:\users\ad\documents\project1_venv\lib\site-packages (from -r requirements.txt (line 3)) (1.7.2)
Requirement already satisfied: matplotlib in c:\users\ad\documents\project1_venv\lib\site-packages (from -r requirements.txt (line 4)) (3.10.7)
Requirement already satisfied: seaborn in c:\users\ad\documents\project1_venv\lib\site-packages (from -r requirements.txt (line 5)) (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ad\documents\project1_venv\lib\site-packages (from pandas->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ad\documents\project1_venv\lib\site-packages (from pandas->-r requirements.txt (line 2)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ad\documents\project1_venv\lib\site-packages (from pandas->-r requirements.txt (line 2)) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in c:\users\ad\documents\project1_venv\lib\site-packages (from scikit-learn->-r requirements.txt (line 3)) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\ad\documents\project1_venv\lib\site-packages (from scikit-learn->-r requirements.txt (line 3)) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\ad\documents\project1_venv\lib\site-packages (from scikit-learn->-r requirements.txt (line 3)) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\ad\documents\project1_venv\lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\ad\documents\project1_venv\lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\ad\documents\project1_venv\lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\ad\documents\project1_venv\lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\ad\documents\project1_venv\lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\ad\documents\project1_venv\lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\ad\documents\project1_venv\lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (3.2.5)
Requirement already satisfied: six>=1.5 in c:\users\ad\documents\project1_venv\lib\site-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 2)) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import os

## Loading and reading dataset

In [3]:
df = pd.read_csv('emails.csv')

In [4]:
df.head()

,Email No.,the,to,ect,and,for,of,a,you,hou,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
0,Email 1,0,0,1,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Email 2,8,13,24,6,6,2,102,1,27,...,0,0,0,0,0,0,0,1,0,0
2,Email 3,0,0,1,0,0,0,8,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Email 4,0,5,22,0,5,1,51,2,10,...,0,0,0,0,0,0,0,0,0,0
4,Email 5,7,6,17,1,5,2,57,0,9,...,0,0,0,0,0,0,0,1,0,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5172 entries, 0 to 5171
Columns: 3002 entries, Email No. to Prediction
dtypes: int64(3001), object(1)
memory usage: 118.5+ MB

In [6]:
df['Prediction'].value_counts()

Prediction
0    3672
1    1500
Name: count, dtype: int64

## Splitting dataset

In [7]:
X = df.iloc[:, 1:3001]
X

,the,to,ect,and,for,of,a,you,hou,in,...,enhancements,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry
0,0,0,1,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,8,13,24,6,6,2,102,1,27,18,...,0,0,0,0,0,0,0,0,1,0
2,0,0,1,0,0,0,8,0,0,4,...,0,0,0,0,0,0,0,0,0,0
3,0,5,22,0,5,1,51,2,10,1,...,0,0,0,0,0,0,0,0,0,0
4,7,6,17,1,5,2,57,0,9,3,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5167,2,2,2,3,0,0,32,0,0,5,...,0,0,0,0,0,0,0,0,0,0
5168,35,27,11,2,6,5,151,4,3,23,...,0,0,0,0,0,0,0,0,1,0
5169,0,0,1,1,0,0,11,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5170,2,7,1,0,2,1,28,2,0,8,...,0,0,0,0,0,0,0,0,1,0
5171,22,24,5,1,6,5,148,8,2,23,...,0,0,0,0,0,0,0,0,0,0

In [8]:
y = df.iloc[:,-1].values
y

array([0, 0, 0, ..., 1, 1, 0], shape=(5172,))

In [9]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

## Hard margin SVM
Giá trị của C ở đây chỉ đơn giản là một giá trị vô cùng lớn, để đảm bảo việc thực hiện Hard margin classifier. Sẽ có giải thích ở phía dưới trong phần Soft margin SVM.

In [10]:
hard_svc = SVC(kernel = 'linear', C=1e6)
hard_svc.fit(x_train, y_train)
print("Accuracy score of Hard marign SVM for training set:", accuracy_score(hard_svc.predict(x_train), y_train))
print("Accuracy score of Hard marign SVM for testing set:", accuracy_score(hard_svc.predict(x_test), y_test))

Accuracy score of Hard marign SVM for training set: 1.0
Accuracy score of Hard marign SVM for testing set: 0.9497293116782676

## Soft margin SVM
Do Hard margin SVM có hiệu suất phân loại kém trong các trường hợp có nhiễu, hoặc không thể hoạt động trong trường hợp dữ liệu không *linearly separable* nên Soft margin SVM sẽ được sử dụng thường xuyên. Lưu ý: Soft margin SVM chỉ hoạt động hiệu quả với dữ liệu gần *linearly separable*.  
Nguyên tắc hoạt động của thuật toán Soft margin SVM là sẽ chấp nhận *missclasify* một vài điểm trong *training set* để thu được mặt phẳng phân loại tốt (có giá trị margin lớn), mang lại hiệu suất phân loại tốt hơn. Nhưng nếu *missclasify* quá nhiều điểm trong *training set* thì hiệu suất phân loại lại kém đi, điều này sẽ được quyết định bởi người thực hiện thông qua điều chỉnh tham số *regularization* C. Nếu C quá lớn hoặc tiến dần đến vô cùng thì thuật toán sẽ chỉ cho phép *missclasify* một số ít điểm, giá trị margin sẽ gần giống với trường hợp sử dụng Hard margin SVM; người lại nếu C quá nhỏ thì thuật toán cho phép *missclasify* nhiều điểm hơn, giá trị margin sẽ lớn hơn. Đây chính là lý do vì sao ở trên kia tôi đã đặt C = 1e6 - một giá trị rất lớn.  
Dưới đây, tôi sẽ tiến hành thực hiện Soft Margin SVM với 3 giá trị C khác nhau: C = 1e-6(rất nhỏ), C = 100(bình thường), C = 1e6(rất lớn)

In [11]:
svc = SVC(kernel = 'linear', C=1e-6)
svc.fit(x_train, y_train)
print("Accuracy score of Soft marign SVM(C=1e-6) for training set:", accuracy_score(svc.predict(x_train), y_train))
print("Accuracy score of Soft marign SVM(C=1e-6) for testing set:", accuracy_score(svc.predict(x_test), y_test))

Accuracy score of Soft marign SVM(C=1e-6) for training set: 0.7385924207269915
Accuracy score of Soft marign SVM(C=1e-6) for testing set: 0.7177107501933488

In [12]:
svc = SVC(kernel = 'linear', C=100)
svc.fit(x_train, y_train)
print("Accuracy score of Soft marign SVM(C=100) for training set:", accuracy_score(svc.predict(x_train), y_train))
print("Accuracy score of Soft marign SVM(C=100) for testing set:", accuracy_score(svc.predict(x_test), y_test))

Accuracy score of Soft marign SVM(C=100) for training set: 1.0
Accuracy score of Soft marign SVM(C=100) for testing set: 0.9497293116782676

In [13]:
svc = SVC(kernel = 'linear', C=1e6)
svc.fit(x_train, y_train)
print("Accuracy score of Soft marign SVM(C=1e6) for training set:", accuracy_score(svc.predict(x_train), y_train))
print("Accuracy score of Soft marign SVM(C=1e6) for testing set:", accuracy_score(svc.predict(x_test), y_test))

Accuracy score of Soft marign SVM(C=1e6) for training set: 1.0
Accuracy score of Soft marign SVM(C=1e6) for testing set: 0.9497293116782676